### ISSUE TITLE
Implementing HNSW (wip)

### ISSUE THREAD

**Issue by kc2853** [bwindsor22/thistle#4]
https://github.com/rust-cv/hnsw
https://github.com/jean-pierreBoth/hnswlib-rs
https://github.com/granne/granne

**Comment by bwindsor22** [comment]
See https://github.com/rust-cv/hnsw/issues/20

**Comment by kc2853** [comment]
https://github.com/rust-cv/hnsw
* Seems like a no-go
* The metric itself isn't tailored towards Euclidean, and in fact it says it might be a bit unstable with Euclidean, see: https://github.com/rust-cv/hnsw/blob/master/tests/simple.rs
* Issue you pointed out

https://github.com/jean-pierreBoth/hnswlib-rs
* Making progress on this one
* There was a build issue compiling `hdf5` so used the following workaround: https://github.com/aldanor/hdf5-rust#conda

**Comment by kc2853** [comment]
* Making some breakthrough, able to run HNSW in our local repo
* I understand where dependencies might break (etc.) now so simplified the import process from the other repo to fit our needs better

**Comment by bwindsor22** [comment]
HNSW -- does 0.7.0 work? https://github.com/rust-cv/hnsw/issues/20#issuecomment-826583442  I can take a look

**Comment by kc2853** [comment]
* Nah, I think that's a no-go b/c even if it builds, the codebase is less relevant for our purposes
* Will try to push my modification of [jean-pierreBoth/hnswlib-rs](https://github.com/jean-pierreBoth/hnswlib-rs) shortly :)

**Comment by kc2853** [comment]
#9 should be modular, so I hope/believe running `cargo test` should still work

**Comment by kc2853** [comment]
#9 finishes this now
